import React, { useEffect, useState } from 'react';
import { BarChart3, Boxes, CircleAlert, DollarSign, Package, RefreshCcw, ShoppingBag, Users } from 'lucide-react';
import api from '../services/api';

const money = value => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(Number(value || 0));

export const Management = () => {
  const [movements, setMovements] = useState([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { api.get('/pos/inventory/movements').then(({ data }) => setMovements(data.data || [])).catch(() => setMovements([])).finally(() => setLoading(false)); }, []);
  const metrics = [
    ['Net sales', '$0.00', DollarSign, 'Today'], ['Completed sales', '0', ShoppingBag, 'Today'],
    ['Average sale', '$0.00', BarChart3, 'Today'], ['Low stock', '0', CircleAlert, 'Needs attention'],
  ];
  return <div className="manage-shell min-h-screen bg-bg-primary text-text-primary"><header className="manage-header"><div><p className="text-xs uppercase tracking-[.2em] text-accent font-bold">Nuvara · Management</p><h1 className="font-display text-3xl mt-1">Good morning, owner</h1></div><button className="manage-refresh" onClick={() => window.location.reload()}><RefreshCcw size={16}/> Refresh</button></header><main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8"><div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-8">{metrics.map(([label,value,Icon,sub]) => <div key={label} className="manage-metric"><div className="manage-icon"><Icon size={18}/></div><p className="text-xs text-text-secondary mt-4">{label}</p><p className="text-2xl font-bold mt-1">{value}</p><p className="text-[11px] text-text-secondary mt-2">{sub}</p></div>)}</div><div className="grid lg:grid-cols-[1.3fr_1fr] gap-6"><section className="manage-card"><div className="flex items-center justify-between mb-6"><div><h2 className="font-display text-2xl">Sales overview</h2><p className="text-sm text-text-secondary mt-1">Completed transactions will appear here.</p></div><span className="manage-pill">Last 7 days</span></div><div className="manage-empty"><BarChart3 size={30}/><p>No sales data yet</p><span>Complete a POS sale to see your trend.</span></div></section><section className="manage-card"><div className="flex items-center justify-between mb-6"><div><h2 className="font-display text-2xl">Inventory activity</h2><p className="text-sm text-text-secondary mt-1">Latest stock adjustments</p></div><Boxes size={20} className="text-accent"/></div>{loading ? <p className="text-sm text-text-secondary">Loading activity…</p> : movements.length ? <ul className="divide-y divide-border">{movements.slice(0,6).map(item => <li key={item.id} className="py-3 flex justify-between text-sm"><span>{item.reason}</span><strong className={item.quantity < 0 ? 'text-danger' : 'text-green-700'}>{item.quantity > 0 ? '+' : ''}{item.quantity}</strong></li>)}</ul> : <div className="manage-empty py-10"><Package size={26}/><p>No inventory movements</p><span>Adjustments and sales will be tracked here.</span></div>}</section></div><div className="manage-card mt-6"><div className="flex items-center gap-3"><Users size={20} className="text-accent"/><div><h2 className="font-display text-2xl">Quick actions</h2><p className="text-sm text-text-secondary mt-1">Operational shortcuts will be enabled as permissions are configured.</p></div></div></div></main></div>;
};
