@extends('layouts.admin')
@section('title','Edit Banner') @section('header_title','Edit Banner')
@section('content')
<div class="max-w-4xl mx-auto glass-card rounded-2xl p-6 sm:p-8">
<div class="flex justify-between items-center mb-6"><div><p class="text-xs uppercase tracking-widest text-brass font-bold">Content studio</p><h2 class="text-2xl font-serif mt-1">Edit banner</h2></div><a href="{{ route('admin.banners') }}" class="text-sm text-gray-400 hover:text-brass">Back to banners</a></div>
<form action="{{ route('admin.banners.update',$banner->id) }}" method="POST" enctype="multipart/form-data" class="grid grid-cols-1 md:grid-cols-2 gap-5">@csrf
@foreach([['title_en','Title',$banner->getLocalized('title','en')],['headline_en','Headline',$banner->getLocalized('headline','en')],['sub_en','Description',$banner->getLocalized('sub','en')],['button_text_en','Button label',$banner->getLocalized('button_text','en')],['link','Link URL',$banner->link]] as $f)<label class="text-xs font-bold uppercase tracking-wider text-brass">{{ $f[1] }}<input name="{{ $f[0] }}" value="{{ $f[2] }}" required class="mt-2 w-full rounded-lg border border-border bg-black/30 px-4 py-3 text-sm text-gray-200"></label>@endforeach
<label class="text-xs font-bold uppercase tracking-wider text-brass">Type<select name="type" class="mt-2 w-full rounded-lg border border-border bg-surface px-4 py-3 text-sm"><option value="hero_slider" @selected($banner->type==='hero_slider')>Hero slider</option><option value="promo_banner" @selected($banner->type==='promo_banner')>Promo banner</option></select></label>
<label class="text-xs font-bold uppercase tracking-wider text-brass">Status<select name="status" class="mt-2 w-full rounded-lg border border-border bg-surface px-4 py-3 text-sm"><option value="1" @selected($banner->status)>Active</option><option value="0" @selected(!$banner->status)>Inactive</option></select></label>
<label class="md:col-span-2 text-xs font-bold uppercase tracking-wider text-brass">Replace image (optional)<input type="file" name="image" accept="image/*" class="mt-2 block w-full rounded-lg border border-border bg-black/30 px-4 py-3 text-sm text-gray-300"><span class="mt-2 block text-[11px] normal-case tracking-normal text-gray-500">Leave empty to keep the current image.</span></label>
<div class="md:col-span-2 flex gap-3 pt-3"><button class="rounded-lg bg-brass px-6 py-3 text-xs font-bold uppercase tracking-widest text-black">Save changes</button><a href="{{ route('admin.banners') }}" class="rounded-lg border border-border px-6 py-3 text-xs font-bold uppercase tracking-widest text-gray-300">Cancel</a></div></form></div>
@endsection
